server:
  port: 8080
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %logger{39} %3L : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    org: info

spring:
  application:
    name: authorization-server

social:
  registration:
    we-chat-test:
      provider: we-chat
      corp-id: lalala
      app-id: lalala
      app-secret: 0lalala
      redirect-uri: http://localhost:8080/social-callback/we-chat/we-chat-test
  provider:
    we-chat:
      scope: snsapi_base
      authorization-uri: https://open.weixin.qq.com/connect/oauth2/authorize
      token-uri: https://qyapi.weixin.qq.com/cgi-bin/gettoken
      user-info-uri: https://qyapi.weixin.qq.com/cgi-bin/user/get