server:
  port: 8080
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %logger{39} %3L : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
spring:
  # database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_learn?serverTimezone=GMT%2B8
    username: root
    password: root