logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %logger{39} %3L : %m%n"
server:
  port: 8080
  servlet:
    session:
      cookie:
        name: auth-test
        domain: localhost
        # 控制浏览器中session id的Cookie的有效期。一般设置为-1,表示随浏览器窗口保持。
        max-age: 7200
        http-only: true
      # 控制session在服务端的持续时间。也就是说session对象在服务端的有效期。一般设置为30分钟。
      # 不建议 server.servlet.session.timeout 小于 server.servlet.session.cookie.max-age
      # 如果项目中使用了 @EnableRedisHttpSession 此处的配置将会无效
      timeout: 7200
spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
  # database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_learn?serverTimezone=GMT%2B8
    username: root
    password: root